// DQSDHost.idl : IDL source for DQSDHost
//

// This file will be processed by the MIDL tool to
// produce the type library (DQSDHost.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(055742ED-C316-4b18-B923-60CE026A9A84),
		dual,
		pointer_default(unique)
	]
  interface IWindowLauncher : IDispatch
  {
    [id(1)] HRESULT OpenWindow([in] BSTR url, [in, optional] VARIANT features);
  };

[
	uuid(6E43F169-92C8-49F7-A554-4950A097DC8E),
	version(1.0),
	helpstring("DQSDHost 1.0 Type Library")
]
library DQSDHostLib
{
	importlib("stdole2.tlb");

	[
		uuid(EC9FE983-E520-4D8F-B1A7-ACBCA0439C70),
		helpstring("DeskBand Class")
	]
	coclass DeskBand
	{
		[default] interface IUnknown;
	};

	[
		uuid(8AD99AB5-C36F-4bd3-A8A6-09FF1686CB59)
	]
	coclass WindowLauncher
	{
		[default] interface IWindowLauncher;
	};

};
